#pragma once

#include "factorymap.h"

const std::vector<std::string> mapPattern1
{     "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    , "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    , "GGWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWGG"
    , "GGWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWGG"
    , "GGWWFFFFFFFFFFFFFFFFFFFFFFFFFFFFWWGG"
    , "GGWWFFFFFFFFFFFFFFFFFFFFFFFFFFFFWWGG"
    , "GGWWFFFFFFFFFFFFFFFFFFFFFFFFFFFFWWGG"
    , "GGWWFFFFFFFFFFFFFFFFFFFFFFFFFFFFWWGG"
    , "GGWWFFFFFFFFWWFFFFFFFFFFFFFFFFFFWWGG"
    , "GGWWFFFFFFFFWWFFFFFFFFFFFFFFFFFFWWGG"
    , "GGWWFFFFFFFFWWFFFFFFFFFFFFFFFFFFWWGG"
    , "GGWWFFFFFFFFWWFFFFFFFFFFFFFFFFFFFFGG"
    , "GGWWFFFFFFFFWWFFFFFFFFFFFFFFFFFFFFGG"
    , "GGWWFFFFFFFFWWFFFFFFFFFFFFFFFFFFWWGG"
    , "GGWWFFFFFFFFWWFFFFFFFFFFFFFFFFFFWWGG"
    , "GGWWFFFFFFFFWWFFFFFFFFFFFFFFFFFFWWGG"
    , "GGWWFFFFFFFFFFFFFFFFFFFFFFFFFFFFWWGG"
    , "GGWWFFFFFFFFFFFFFFFFFFFFFFFFFFFFWWGG"
    , "GGWWFFFFFFFFFFFFFFFFFFFFFFFFFFFFWWGG"
    , "GGWWFFFFFFFFFFFFFFFFFFFFFFFFFFFFWWGG"
    , "GGWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWGG"
    , "GGWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWGG"
    , "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    , "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
 };

class TestMap1
{
public:

    static void show(FactoryMap * map);

};


